Code Review
chje118/KU-CPR pull request #1
Opened 2024-09-28 08:03 UTC by chje118

Wanting code review of script

2024-10-02 14:52 UTC, straussmaximilian requested changes
Hi,

this is great code for a first Pull Request! Congratulations. I added some comments, feel free to adjust. 
One main thing you should change before I would approve the PR is to provide more context on what your program does, e.g. updating the readme file. A good starting point can be to dump your code in ChatGPT and ask it to create a Readme.

2024-10-02 14:52 UTC, straussmaximilian commented on FileTransfer_MultipleFolders.py
> +    '''Move source folder into destination folder.
Python doctoring convention suggest to use triple quotation marks `"""` instead of single ones `'''`, although they are technically the same, see https://peps.python.org/pep-0257/

2024-10-02 14:52 UTC, straussmaximilian commented on FileTransfer_MultipleFolders.py
> +            os.makedirs(dest_dir)
`os.makedirs` accepts an input argument `exist_ok`, which can handle existing folders, so you could simplify this line to `os.makedirs(dest_dir, exist_ok=True)`

2024-10-02 14:52 UTC, straussmaximilian commented on FileTransfer_MultipleFolders.py
> +        for file in files:
People always love progress bars, and an easy way to do this is the package `tqdm`. This would then be `for file in tqdm(files)`:

See https://github.com/tqdm/tqdm

2024-10-02 14:52 UTC, straussmaximilian commented on FileTransfer_MultipleFolders.py
> +            if os.path.exists(dest_file):
This function is a good as is.
For some applications it could be that the `dest_file` exists is there but maybe corrupted (e.g. smaller file size). Then it is useful to additionally check if the files are actually the same, or which one is the more likely correct one.

2024-10-02 14:52 UTC, straussmaximilian commented on FileTransfer_MultipleFolders.py
> +def transfer_folder_with_retry(source_folder, destination_folder, max_retries, retry_delay):
Here, it could be useful to set some default arguments for `max_retries` and `retry_delay` with e.g. `max_retries=5`, then you don't need to declare all arguments.

2024-10-02 14:52 UTC, straussmaximilian commented on FileTransfer_MultipleFolders.py
> +                    print("Transfer canceled by user.")
This is a bit unclean as `merge_and_move_folders` could raise an error and it would still say transfer canceled by user. If user cancelation is a keyboard interrupt, you can use try and except to catch a keyboard interrupt like so:

```
try:
    # Code that may raise KeyboardInterrupt
except KeyboardInterrupt:
    # Code to handle the KeyboardInterrupt
```

2024-10-02 14:52 UTC, straussmaximilian commented on FileTransfer_MultipleFolders.py
> +                retry_count = retry_count + 1
This can also be written as increment: `retry_count += 1`

2024-10-02 14:52 UTC, straussmaximilian commented on FileTransfer_MultipleFolders.py
> +                if retry_count <= max_retries:
The code is getting quite nested with if / else  here. If you switch the order a bit and focus on successful execution and then error handling you have less nesting, e.g:

```
if "network error" not in error_message:
    break
retry_count += 1

if retry_count > max_retries:
     raise e

time.sleep(retry_delay)
```

2024-10-02 14:52 UTC, straussmaximilian commented on FileTransfer_MultipleFolders.py
> +        if not os.path.exists(source_folder):
Good error handling here to check for folder existing

2024-10-02 14:52 UTC, straussmaximilian commented on FileTransfer_MultipleFolders.py
> +source_folders = [
It is good to provide an example, however, whenever you import a module the code is executed, so this might be problematic if you build larger programs. A good workaround is to put this in a main function and adding __main__, like so:

https://realpython.com/if-name-main-python/

2024-10-15 13:38 UTC, chje118 commented on FileTransfer_MultipleFolders.py
> +            if os.path.exists(dest_file):
Great, I will add this later.

2024-12-09 14:20 UTC, straussmaximilian commented
This seems to be the old version?
I guess you can merge and we continue with the other branches.

2025-02-05 10:38 UTC, merged